name: backup
services:
  backup2onedrive:
    hostname: anyshpm-ubuntu
    volumes:
      - /home/anyshpm:/home/anyshpm
      - /home/anyshpm/.config/rclone:/root/.config/rclone
    environment:
      - BACKUP_DRIVE_NAME=anyshpm-onedrive
      - BACKUP_DIR=/home/anyshpm
      - BACKUP_USERNAME=anyshpm
      - TZ=Asia/Shanghai
    image: anyshpm/backup
