name: backup
services:
  backup2onedrive:
    hostname: anyshpm-ubuntu
    volumes:
      - /path/to/data:/data
      - /path/to/config/rclone:/root/.config/rclone
    environment:
      - BACKUP_DRIVE_NAME=cloud
      - BACKUP_DIR=/data
      - BACKUP_USERNAME=user
      - TZ=Asia/Shanghai
    image: anyshpm/backup
